# Generated by Django 3.1.2 on 2021-01-30 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210129_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='tweetid',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fromuser', to='network.tweet'),
        ),
    ]
