# Generated by Django 3.1.2 on 2021-02-14 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_tweet_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
    ]
